# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/control.kubestellar.io_workstatuses.yaml

patchesJson6902:
  - path: patch.yaml
    target:
       group: apiextensions.k8s.io
       version: v1
       kind: CustomResourceDefinition
       name: workstatuses.control.kubestellar.io

#+kubebuilder:scaffold:crdkustomizeresource
