name: Add issues to KS project

on:
  issues:
    types:
      - opened
      - reopened
  pull_request_target:
    types: [opened]
    

permissions:
  contents: write
  
jobs:
  create-update-project:
    #if: github.repository_owner == 'kubestellar'
    name: Create/update project issue
    runs-on: ubuntu-latest
    steps:
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
        
      - uses: actions/checkout@v4.1.1
        with:
     #     token: ${{ secrets.GH_ALL_PROJECT_TOKEN }}
          persist-credentials: 'false'
      
      - uses: actions/add-to-project@v1.0.1 # This adds the issue to the project
        with:
          project-url: https://github.com/orgs/kubestellar/projects/5
          github-token: ${{  secrets.GITHUB_TOKEN }}
        id: add-project
      
      - uses: titoportas/update-project-fields@v0.1.0
        with:
          project-url: https://github.com/orgs/kubestellar/projects/5
          github-token: ${{  secrets.GITHUB_TOKEN }}
          item-id: ${{ steps.add-project.outputs.itemId }} # Use the item-id output of the previous step
          field-keys: Status,Date Posted
          field-values: New,${{ steps.date.outputs.date }}
